### ISSUE TITLE
Don't create objects without a required value populated

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#89]
This hard-to-prevent issue is appearing here and there across all our scripts: 

e.g. circulation notes without the note value
notes without a note value
addresses with only an address type

**Comment by branchedelac** [comment]
Do you mean it a value is "0"? 

What I was thinking is we should remove/not create objects where the "main" value is "" in cases where we know that these will not be meaningful to the library and are likely to cause UI errors. We've had quite a few issues with addresses especially.

If we should ever consider 0 or en other character equivalent to empty I think that could be defined and homogenized in the prep stage.

**Comment by fontanka16** [comment]
There are some different opinions on if a zero-value should equate to an empty field or not, but I guess, that should be handled in Data prep. 

So I guess I agree, that if there is anything else than the empty string or whitespace in there, then we create a note.

**Comment by fontanka16** [comment]
@branchedelac  we need to handle these ones case-by-case if these props are not required.

**Comment by fontanka16** [comment]
@branchedelac I created #177  for the last piece you mention. 

I believe we should report these issues to the community as we go along, if the issue is that the props do not come through as required in the schemas. Of course we need to handle them as well.

https://github.com/FOLIO-FSE/folio_migration_tools/commit/b745f843a96d9132effedf63f30dfc6b9f4d7739 fixes the circ notes thing.
